FROM golang:1.22-alpine AS builder
ARG TARGET=notification-worker
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /moistello-worker ./cmd/${TARGET}

FROM alpine:3.20
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /moistello-worker /usr/bin/moistello-worker
COPY config/ /etc/moistello/
ENTRYPOINT ["/usr/bin/moistello-worker"]
